### ISSUE TITLE
vue slate with Nuxt

### ISSUE THREAD

**Issue by regenrek** [marsprince/slate-vue#15]
Hi,

I have some problems to get this running with nuxt

![image](https://user-images.githubusercontent.com/5182020/89617768-186be780-d88b-11ea-9f20-0dee7e51f762.png)

Here is an example
https://github.com/regenrek/nuxt-vue-slate-example

https://codesandbox.io/s/vibrant-pascal-detwb (don't think this will work)

Regards

**Comment by marsprince** [comment]
@regenrek Thank you for your feedback！I will test Nuxt running and correct it in this week
