### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by paul-asvb** [marsprince/slate-vue#23]
Wanted to checkout slate-vue.
`
Vue.use(SlatePlugin)
`
Version:
"vue": "^2.6.10"

Error i got:

vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <editor-slate> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by marsprince** [comment]
@paul-asvb Any example? I know what the problem is(I didn't write name) and need to reproduce it.
