### ISSUE TITLE
$editor.insertText doesn't work without focus

### ISSUE THREAD

**Issue by tre-dev** [marsprince/slate-vue#43]
I'm trying to add emojis via emoji-picker programmatically via `this.$editor.insertText(emoji)`.

But it only works once or twice after I add the focus manually, afterwards the focus is gone and emojis can't be added unless I add focus manually again. Adding focus programmatically doesn't work as it resets the cursor position.

**Comment by marsprince** [comment]
@tre-dev 
Any simple example that I can reproduce it ?
I guess that when you use emoji-picker, you lose selection in slate.So slate doesn't know where to insert.

**Comment by tre-dev** [comment]
Hm, that could be. Here is a rough example.

```
<template>
  <div>
    <Slate ref="slate" :value="value">
      <Editable ref="editor"" />
    </Slate>
    <Button @click="addEmoji">
      Add Emoji
    </Button>
  </div>
</template>

// script

value = JSON.stringify({children: [{text: ''}]})

addEmoji() {
    this.$editor.insertText('😊')
  }
```

**Comment by tre-dev** [comment]
Maybe it's possible to get the current/last cursor position and then insert the Text at that position?

Code below is adding an emoji like this but at an incorrect position

```
text1

!<EMOJI_WAS_ADDED_HERE> text 2
```

```
addEmoji(emoji) {
    const slateChildren = document.querySelector('[data-slate-editor]').children
    const range = new Range()
    range.setStartAfter(slateChildren[slateChildren.length - 1])
    Transforms.insertText(this.$editor, emoji, {
      at: VueEditor.toSlateRange(this.$editor, range),
    })
  }
```

**Comment by marsprince** [comment]
@tre-dev 
I wrote a simple example with library vue-emoji-picker
https://github.com/marsprince/slate-vue/commit/f241ef2c7dfa7eb53756fe3c44f5b352f7e5c296

If it's not what's you want, look at this issue https://github.com/ianstormtaylor/slate/issues/3412. I use the final solution and you can try others.

**Comment by tre-dev** [comment]
The example you wrote worked! Thanks!

Magic code was this:

```
 Transforms.insertNodes(
      this.$editor,
      {
        text: emoji,
        emoji: true,
      },
      {
        at: this.$editor.savedSelection,
      },
    )
```

PS: FYI, I actually prefer this emoji-picker https://github.com/serebrov/emoji-mart-vue
