### ISSUE TITLE
Mouse Selection

### ISSUE THREAD

**Issue by kamunds** [marsprince/slate-vue#58]
First, thanks for the effort in porting Slate to Vue.  I do, however, see an issue I'm not sure how to solve myself.

If you use your mouse to highlight text across multiple paragraphs that include an empty paragraph in the middle, the selection stops and the cursor just moves.  This only happens when selecting text going UP in the document.  It works fine going down.  You can replicate this in any of your online samples.

Start with some text:

line one is this one
line two is this one

line four is this one - line three is an empty line
line five is this one

To replicate it, simply use your mouse and try to select the text, starting at line five and drag up to line one.

**Comment by marsprince** [comment]
I got the problem and will be fixed in this week when I have enough time. Thank you for your feedback.
