### ISSUE TITLE
Examples not supported Firefox

### ISSUE THREAD

**Issue by yarmak** [marsprince/slate-vue#59]
[https://marsprince.github.io/slate-vue/#/richtext](https://marsprince.github.io/slate-vue/#/richtext) 
Simple typing in Firefox is lost after pressing the Enter button.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2275612/98503367-e9e51a80-2286-11eb-91b4-352ad861cf85.gif)

Here [https://www.slatejs.org/examples/richtext](https://www.slatejs.org/examples/richtext) there is no such problem

**Comment by marsprince** [comment]
Thank you for your feedback. I only tested examples in Chrome. Need time to test and fix in other browsers.

**Comment by marsprince** [comment]
Fixed in v0.2.0
