### ISSUE TITLE
How to integrate a slate plugin with vue-slate

### ISSUE THREAD

**Issue by Hen2609** [marsprince/slate-vue#71]
Hi, first of all i wanted to say i was very excided to see this repo, it's exactly what i wanted to do, build my editor in slate and integrate it with vue.
wanted to ask if [plugins ](https://docs.slatejs.org/concepts/07-plugins) are supported? 
how can i integrate my slate js plugins with vue-slate?  
thanks :)

**Comment by marsprince** [comment]
There are no need to integrate in my understanding. Just use it in [editoredCreated hook](https://github.com/marsprince/slate-vue/tree/master/packages/slate-vue#get-editor-instance).
