### ISSUE TITLE
Can't get it to work in NuxtJS

### ISSUE THREAD

**Issue by SirWindfield** [marsprince/slate-vue#73]
This is probably just a configuration error, but seeing that #15 isn't related I thought I might open a new one. I have added `slate-vue` to my Nuxt project and enabled the plugin in `nuxt.config.js`.
```js
// plugins/vue-slate.js
import Vue from 'vue'
import { SlatePlugin } from 'slate-vue'

Vue.use(SlatePlugin)
```

```js
// nuxt.config.js
{
  build: {
    transpile: ['slate-vue']
  },
  plugins: ['~/plugins/vue-slate.js'],
}
```

I still experience the `Unexpected token 'export'` error. That's why I added the package to the transpile key in the first place. As soon as I remove the plugin file reference from the `plugins` array, the website loads fine.

__Edit:__ I've uploaded the project: https://github.com/SirWindfield/zt-write. It's basically just the default template (`yarn create nuxt-app zt-write`) with `slate-vue` added and configured.

**Comment by SirWindfield** [comment]
Looks like the plug-in only works when disabling ssr, not sure why though.

**Comment by SirWindfield** [comment]
Sorry to re-open this but for some reason it doesn't work again today. I used the exact same project that I had yesterday with ssr disabled but that fails today. Cleaned cache and everything. Maybe someone else has/had similar issues...

**Comment by marsprince** [comment]
I don't have enough time to test. You can set ``mode: 'SPA'`` as a temporary solution. I will test it this weekend.

**Comment by SirWindfield** [comment]
Thank you for taking the time to try it out!

**Comment by marsprince** [comment]
I have done some tests and found the problems. The module for tsx support: ``vue-tsx-support@3.1.0`` only has ES6 dist version. 
Just add it to transpile option like :
``
build: {
    transpile: ['slate-vue', 'vue-tsx-support']
  }
``

**Comment by SirWindfield** [comment]
Oh, the trick is to add both of them, dang. I only added `slate-vue`. Thanks!!!

**Comment by rxsto** [comment]
JFYI, you can get this to work with SSR (and e.g. the static target) when wrapping the `<Slate>` component in `<client-only>` in order to bypass prerendering for this specific part of the code. https://nuxtjs.org/docs/features/nuxt-components/#the-client-only-component
